print('how are you')
print('happy')
print('are you ok')
print('yes')
print('how many friends do you have')
print('more than I can count')
print('why are you here')
print('because I dont know what to do yeah')
print('what do you think about Peter teacher')
print('boring lessons')